import assert from "node:assert/strict";
import { remindersFor, shortReminder, winLine, greetingTitle } from "./push-math";
import type { ForecastEvent } from "./forecast-math";

const e = (o: Partial<ForecastEvent>): ForecastEvent => ({ id: "x", date: "2026-10-06", dueDate: "2026-10-06", label: "Chase Sapphire", cents: -130000, kind: "card", remindDays: 5, ...o });
const t = "2026-10-05";
let r = remindersFor([e({})], t, "wp");
assert.equal(r.length, 1);
assert.equal(r[0].key, "wp:x:2026-10-06:early");
assert.equal(r[0].text, "Chase Sapphire ($1,300.00) is coming up tomorrow");
r = remindersFor([e({ dueDate: "2026-10-05", date: "2026-10-05" })], t, "wp", "Business: ");
assert.equal(r[0].key, "wp:x:2026-10-05:day");
assert.equal(r[0].text, "Business: Chase Sapphire ($1,300.00) is coming up today");
assert.equal(remindersFor([e({ dueDate: "2026-10-20", date: "2026-10-20" })], t, "wp").length, 0, "outside the window");
assert.equal(remindersFor([e({ remindDays: undefined })], t, "wp").length, 0, "no reminder wanted");
r = remindersFor([e({ dueDate: "2026-10-01", date: t, label: "Rent" })], t, "wp");
assert.equal(r[0].text, "Rent ($1,300.00) is waiting for you");
r = remindersFor([e({ kind: "recurring", label: "Payroll tax", remindDays: 0, dueDate: t, date: t })], t, "wp");
assert.equal(r[0].text, "Payroll tax is ready to post");
assert.equal(remindersFor([e({ kind: "recurring", remindDays: 0 })], t, "wp").length, 0, "tomorrow is outside a same-day window");
assert.equal(shortReminder("wp", "", { date: "2026-11-14", cents: -34810 }, t), null);
assert.equal(shortReminder("wp", "", { date: "2026-10-14", cents: -34810 }, t)!.text, "There's a $348.10 gap to plan for around Oct 14. You have 9 days to arrange it.");
r = remindersFor([e({ id: "card-close:c1", label: "Pay down Chase Sapphire", cents: -40000 })], t, "wp");
assert.equal(r[0].text, "Chase Sapphire: a $400.00 payment tomorrow keeps your credit use low");
r = remindersFor([e({ id: "card-due:c1", label: "Pay Amex Gold", cents: -520000, dueDate: "2026-10-07", date: "2026-10-07" })], t, "wp");
assert.equal(r[0].text, "Amex Gold payment of $5,200.00 is due on Oct 7");
assert.equal(winLine(500000, true), "$5,000.00 is on its way in over the next 30 days.");
assert.equal(winLine(0, false), "Your next 30 days look covered.");
assert.equal(winLine(0, true), null);
assert.equal(greetingTitle(" Mike "), "Good morning, Mike");
for (const x of remindersFor([e({ dueDate: "2026-10-01", date: t })], t, "wp")) assert.ok(!/overdue|short|urgent|warning|alert/i.test(x.text));
console.log("push-math ok");
